name: 'My Action'
description: 'An example action'
inputs:
  work-dir:
    description: 'Working directory'
    required: true
    default: '/tmp'
runs:
  using: 'composite'
  steps:
    - name: testing
      run: pwd && cd ${{ inputs.work-dir }} && pwd
