# name: 'My Action'
# description: 'An example action'
# inputs:
#   work-dir:
#     description: 'Working directory'
#     required: true
#     default: '/tmp'
#   branch:
#     default: $GITHUB_REF_NAME
#   url:
#     default: $GITHUB_SERVER_URL/$GITHUB_REPOSITORY
# runs:
#   using: 'composite'
#   steps:
#     - name: testing work-dir
#       run: pwd && cd ${{ inputs.work-dir }} && pwd
#       shell: bash
     
#     - name: testing branch and url
#       run: 
#       shell: bash 




# # if: github.ref == 'refs/heads/action-ci-cd-test'
# # runs-on: vegaops-config

