# name: 'My Action'
# description: 'An example action'
# inputs:
#   work-dir:
#     description: 'Working directory'
#     required: true
#     default: '/tmp'
#   branch:
#     default: $GITHUB_REF_NAME
#   url:
#     default: $GITHUB_SERVER_URL/$GITHUB_REPOSITORY
# runs:
#   using: 'composite'
#   steps:
#     - name: testing work-dir
#       run: pwd && cd ${{ inputs.work-dir }} && pwd
#       shell: bash
     
#     - name: testing branch and url
#       run: 
#       shell: bash 


name: Testing PeerXP Action
on: [push]

jobs:
  PROD_DEPLOY:
    runs-on: vegaops-config
    steps:
      - uses: vs-ops-bot/Action-Runner-CI-CD/PeerXP@Test-1
        with:
          branch: $GITHUB_REF_NAME
          dir: '/var/vegaops/config'



# # if: github.ref == 'refs/heads/action-ci-cd-test'
# # runs-on: vegaops-config

