name: 'My Action'
description: 'An example action'
inputs:
  work-dir:
    description: 'Working directory'
    required: true
    default: '/tmp'
runs:
  using: 'composite'
  steps:
    - name: testing
      run: pwd && cd ${{ inputs.work-dir }} && pwd
      shell: bash

# name: 'Testing vegaops-config'
# on:
#   push:
#     branches:  'Test-1'

# jobs: 
#     PROD_DEPLOY:
#       runs-on: vegaops-config
#       steps:
#         - run: | 
#             sudo chmod -R 775 ./*
#             git add . && git commit --allow-empty -m "updated permissions"
#             echo "prod path and project name"
#             echo $PROD_PATH
#             echo $CI_PROJECT_NAME
#             cd $PROD_PATH/$CI_PROJECT_NAME
#             git config --global --add safe.directory $PROD_PATH/$CI_PROJECT_NAME
#             pwd
#             git fetch $CI_REPOSITORY_URL
#             git checkout -B master origin/master
#             git pull $CI_REPOSITORY_URL $CI_COMMIT_BRANCH
#             sudo chmod -R 775 ./*
#             git add . && git commit --allow-empty -m "updated permissions"
        

# PROD_DEPLOY:
#     stage: deploy
#     script:
#         - sudo chmod -R 775 ./*
#         - git add . && git commit --allow-empty -m "updated permissions"
#         - echo "prod path and project name"
#         - echo $PROD_PATH
#         - echo $CI_PROJECT_NAME
#         - cd $PROD_PATH/$CI_PROJECT_NAME
#         - git config --global --add safe.directory $PROD_PATH/$CI_PROJECT_NAME
#         - pwd
#         - git fetch $CI_REPOSITORY_URL
#         - git checkout -B master origin/master
#         - git pull $CI_REPOSITORY_URL $CI_COMMIT_BRANCH
#         - sudo chmod -R 775 ./*
#         - git add . && git commit --allow-empty -m "updated permissions"

#     environment:
#         name: vegaops-config
#         url: https://config.vegaops.com/
#     # when: manual
#     tags:
#         - vegaops-config
#     only:
#         refs:
#              - master

