name: Action Runner Testing
on: 
  push:
    branches: [main]

jobs:
  job1:
    runs-on: shell-runner
    steps:
      - uses: actions/checkout@v4
      - run: echo "job1 is succeeded with shell-runner"
