name: Action Runner Testing
on: 
  push:
    branches: [main]

  workflow_dispatch:

jobs:
  job1:
    runs-on: shell-runner
    steps:
      - uses: actions/checkout@v4
      - run: ls /root
