# name: Action Runner Testing
# on: 
#   push:
#     branches: [main]

# jobs:
#   job1:
#     runs-on: shell-runner
#     steps:
#       - uses: actions/checkout@v4
#       - run: ls /root

name: Testing PeerXP Action
on: [push]

jobs:
  PROD_DEPLOY:
    runs-on: vegaops-config
    steps:
      - uses: vs-ops-bot/Action-Runner-CI-CD/PeerXP@Test-1
        with:
          branch: $GITHUB_REF_NAME
          dir: '/var/vegaops/config'
