# name: Action Runner Testing
# on: 
#   push:
#     branches: [main]

# jobs:
#   job1:
#     runs-on: shell-runner
#     steps:
#       - uses: actions/checkout@v4
#       - run: ls /root

name: Testing PeerXP Action
on: [push]

jobs:
  PROD_DEPLOY:
    runs-on: ubuntu-latest
    steps:
      - uses: ./PeerXP@Test-1
        with:
          branch: $GITHUB_REF_NAME
          dir: '/home/ubuntu/'
        # env:
        #   GITHUB_TOKEN: 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
          
