name: Request review on PRs

on:
  pull_request:
    types:
      - opened

jobs:
  request:
    name: Request reviews on opened PRs
    runs-on: ubuntu-latest

    steps:
      - name: Create PR review request
        env:
          GITHUB_TOKEN: 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
          url: ${{ github.event.pull_request.html_url }}
        run: |
          gh pr edit "$url" --add-reviewer Vegastack/vs-ops-bot



